### PR TITLE
Metric add: ups.temperature

### PR DESCRIPTION
**Pull request by uncleBorsch**

### CODE REVIEW

**Comment by HON95** [comment]
Thanks! A few things I'd like to see changed, though. 

Please add "_celsius" to the metric name, per Prometheus best pactices ("[...] should have a suffix describing the unit, in plural form.").

And could you remove ", degrees C" and add a period in the description/help? The unit doesn't need to be everywhere.

And could you add it to the table in the README? The ordering is (roughly) the same as in the source code.

And ignore the failed check, I need to fix the linting of the rest of the code after the linter suddenly became pickier ...

**Comment by uncleBorsch** [comment]
"_celsius" suffix added to metric name, "degrees C" removed from help, units changed to "degrees C"
README updated.

I'm not sure what kind of period should be added for temperature. feel free to change.

**Comment by HON95** [comment]
Nice. Since it's just documentation-like changes, I can just change it after merging/squashing. Do you mind if I remove the `_ups_` part though, since the other metrics don't use it?

**Comment by uncleBorsch** [comment]
sure. remove it )

**Pull request merged**
